@echo off
echo Cleaning Gradle cache...
cd android
call gradlew clean
cd ..
echo Deleting build folder...
rmdir /s /q build
echo Cleaning Flutter...
flutter clean
echo All clean! Now building...
flutter build apk --debug