name: BMS
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  #Utility Packages

  #Web Specific

  #State Management

  #Firebase
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  dio: ^5.4.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_bloc: ^8.1.3
  crypto: ^3.0.3 # Added for certificate fingerprinting
  equatable: ^2.0.5
  delightful_toast: ^1.0.3
  toastification: ^1.1.0
  lottie: ^3.3.0
  url_launcher: ^6.1.10
  app_links: ^3.4.1
  # webview_flutter: ^4.4.2
  flutter_inappwebview: ^6.0.0
  archive: ^3.3.7
  # Secure Storage
  # flutter_secure_storage: ^4.2.1
  # encrypt: ^5.0.3
  xml: ^6.3.0
  device_info_plus: 11.5.0
  package_info_plus: ^8.3.1
  flutter_jailbreak_detection: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/lnt_finance/LTFinance_logo.png"
  adaptive_icon_background: "#f3db21"
  adaptive_icon_foreground: "assets/logos/lnt_finance/LTFinance_logo.png"

flutter_native_splash:
  color: "#FFC107"
  android: true
  ios: true
  android_gravity: "center"
  ios_content_mode: "center"

flutter:
  uses-material-design: true

  #-----LOCAL ASSETS------#

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/data/ml/
    - assets/data/nonml/
    - assets/fonts/
    - assets/logos/
    - assets/logos/lnt_finance/
    - assets/logos/lnt_finance/LTF_logo.png
    - assets/logos/lnt_finance/temp_logo.png
    - assets/animations/
    - assets/animations/Loading1.json
    - assets/animations/successAnimation.json
    - assets/animations/failedAnimation.json
    - assets/animations/downloadAnimation.json
    - assets/animations/DataList.json
    - assets/animations/NoTasks.json
    - assets/certificate/wildcard.ltfinance.com.pem
    - assets/certificate/wildcard.ltfinance.com.key
    - assets/certificate/login.salesforce.crt
  #---------LOCAL FONTS---------#
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Black.otf
          weight: 900
        - asset: assets/fonts/PlayfairDisplay-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Italic.otf
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Regular.otf
    - family: PlayfairDisplaySC
      fonts:
        - asset: assets/fonts/PlayfairDisplaySC-Black.otf
          weight: 900
        - asset: assets/fonts/PlayfairDisplaySC-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/PlayfairDisplaySC-Bold.otf
          weight: 700
        - asset: assets/fonts/PlayfairDisplaySC-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/PlayfairDisplaySC-Italic.otf
          style: italic
        - asset: assets/fonts/PlayfairDisplaySC-Regular.otf
